// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Notification struct {
	ID     string  `json:"id"`
	Input  *string `json:"input"`
	Output *string `json:"output"`
}

type NotificationInput struct {
	Input  *string `json:"input"`
	Output *string `json:"output"`
}
