apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "zicops-notification-server.fullname" . }}
  labels:
    {{- include "zicops-notification-server.labels" . | nindent 4 }}
 spec:
      containers:
        {{ $zcbcred := printf "%s/%s" .Values.zcServiceAccount.credential.dir .Values.zcServiceAccount.credential.file }}
        - name: {{ .Chart.Name }}-asp
          image: "{{ .Values.asp.repository }}:{{ .Values.asp.tag }}"
          imagePullPolicy: {{ .Values.asp.pullPolicy }}
          args: [
            "--port={{ .Values.asp.port }}",
            "--backend=http://127.0.0.1:{{ .Values.image.port }}",
            "--mode={{ .Values.asp.arg.mode }}",
          ]
          volumeMounts:
          - name: zicops-cc
            mountPath: {{ .Values.zcServiceAccount.credential.dir | quote }}
            readOnly: true
          env:
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: {{ $zcbcred }}
          ports:
            - name: http-server-ns
              containerPort: {{ .Values.asp.port }}
              protocol: TCP
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.image.port }}
          readinessProbe:
            httpGet:
              path: {{ .Values.image.health }}
              port: {{ .Values.image.port }}
            initialDelaySeconds: 5
            timeoutSeconds: 1  
          volumeMounts:
          - name: zicops-cc
            mountPath: {{ .Values.zcServiceAccount.credential.dir | quote }}
            readOnly: true
          - name: zdevastracert
            mountPath: {{ .Values.zcCertAstra.cert.dir | quote }}
            readOnly: true
          - name: zdevastracertca
            mountPath: {{ .Values.zcCertCAAstra.cert.dir | quote }}
            readOnly: true
          - name: zdevastrakey
            mountPath: {{ .Values.zcAstraKey.key.dir | quote }}
            readOnly: true
          env:
          - name: PORT
            value: {{ .Values.image.port | quote }}
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: {{ $zcbcred }}
      volumes:
      - name: zicops-cc
        secret:
          secretName: {{ .Values.zcServiceAccount.secret }}
