apiVersion: v1
kind: Service
metadata:
  name: {{ include "zicops-notification-server.fullname" . }}
  labels:
    {{- include "zicops-notification-server.labels" . | nindent 4 }}
spec:
  type: { { .Values.service.type } }
  ports:
    - port: { { .Values.service.port } }
      targetPort: http-server-um
      protocol: TCP
      name: http-server-cq
  selector:
    {{- include "zicops-notification-server.selectorLabels" . | nindent 4 }}