apiVersion: v1
kind: Service
metadata:
  name: {{ include "zicops-notification-server.name" . }}
  labels:
    app: {{ template "zicops-notification-server.name" . }}
    chart: {{ template "zicops-notification-server.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http-server-ns
      protocol: TCP
      name: http-server-not
  selector:
    app: {{ template "zicops-notification-server.name" . }}
    release: {{ .Release.Name }}
