apiVersion: v1
kind: Service
metadata:
  name: "zicops-notification-server"
  labels:
    app: "zicops-notification-server"
    chart: "zicops-notification-server-0.1.0"
    release: "zicops-notification-server"
    heritage: "Helm"
spec:
  type: { { .Values.service.type } }
  ports:
    - port: { { .Values.service.port } }
      targetPort: http-server-ns
      protocol: TCP
      name: http-server-ns
  selector:
    app: { { template "zicops-notification-server.name" . } }
    release: { { .Release.Name } }
