name: ZICOPS UM-CICD(reusable flow)
on:
  workflow_call:

    inputs:
      GKE_CLUSTER: 
       required: true
       type: string
      GKE_ZONE:
       required: true
       type: string
      NAMESPACE:
       required: true
       type: string
      SERVICE_NAME:
       required: true
       type: string
      
      
    secrets:
      PROJECT_ID:
        required: true  



jobs:
  Push_GCP__Deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Push image to GCP
        run: docker push gcr.io/${{ secrets.PROJECT_ID }}/${{ inputs.SERVICE_NAME }}:${GITHUB_SHA}
        
      - name: Push image to GCP
        run: docker push gcr.io/${{ secrets.PROJECT_ID }}/${{ inputs.SERVICE_NAME  }}:latest
        
      - name: replace environment variable in values.yaml
        run: envsubst '${GITHUB_SHA}' < k8s/zicops-notification-server/values.template.yaml >  k8s/zicops-notification-server/values.yaml
        
      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
          
      - name: Deploy to zicops 
        run: |
          gcloud container clusters get-credentials $GKE_CLUSTER \
            --zone ${{ inputs.GKE_ZONE }} \
            --project ${{ secrets.PROJECT_ID }}
          helm upgrade zicops-notification-server k8s/zicops-notification-server -n ${{ inputs.NAMESPACE }} --install --wait --atomic
          

